package br.com.bluesi.mailmonitor.entities;
// Generated 10/08/2017 21:38:25 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgrupamentoOcorrencia generated by hbm2java
 */
@Entity
@Table(name = "agrupamento_ocorrencia", catalog = "opsblue")
public class AgrupamentoOcorrencia implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Date dataAssociacao;
	private String palavrasChaves;
	private Date dataCriacao;
	private Set<Ocorrencia> ocorrencias = new HashSet<Ocorrencia>(0);

	public AgrupamentoOcorrencia() {
	}

	public AgrupamentoOcorrencia(String nome, Date dataCriacao) {
		this.nome = nome;
		this.dataCriacao = dataCriacao;
	}

	public AgrupamentoOcorrencia(String nome, Date dataAssociacao, String palavrasChaves, Date dataCriacao,
			Set<Ocorrencia> ocorrencias) {
		this.nome = nome;
		this.dataAssociacao = dataAssociacao;
		this.palavrasChaves = palavrasChaves;
		this.dataCriacao = dataCriacao;
		this.ocorrencias = ocorrencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_associacao", length = 19)
	public Date getDataAssociacao() {
		return this.dataAssociacao;
	}

	public void setDataAssociacao(Date dataAssociacao) {
		this.dataAssociacao = dataAssociacao;
	}

	@Column(name = "palavras_chaves", length = 2000)
	public String getPalavrasChaves() {
		return this.palavrasChaves;
	}

	public void setPalavrasChaves(String palavrasChaves) {
		this.palavrasChaves = palavrasChaves;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", nullable = false, length = 19)
	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrupamentoOcorrencia")
	public Set<Ocorrencia> getOcorrencias() {
		return this.ocorrencias;
	}

	public void setOcorrencias(Set<Ocorrencia> ocorrencias) {
		this.ocorrencias = ocorrencias;
	}

}
