package br.com.bluesi.mailmonitor.entities;
// Generated 10/08/2017 21:38:25 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente",catalog = "opsblue")
public class Cliente implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String endereco;
	private String cnpj;
	private String telefone;
	private String contato;
	private byte[] filterRuleJexl;
	private String usuariosNotificados;
	private Set<Contrato> contratos = new HashSet<Contrato>(0);
	private Set<Ocorrencia> ocorrencias = new HashSet<Ocorrencia>(0);

	public Cliente() {
	}

	public Cliente(String nome, String endereco, String cnpj, String telefone, String contato) {
		this.nome = nome;
		this.endereco = endereco;
		this.cnpj = cnpj;
		this.telefone = telefone;
		this.contato = contato;
	}

	public Cliente(String nome, String endereco, String cnpj, String telefone, String contato, byte[] filterRuleJexl,
			String usuariosNotifcados, Set<Contrato> contratos, Set<Ocorrencia> ocorrencias) {
		this.nome = nome;
		this.endereco = endereco;
		this.cnpj = cnpj;
		this.telefone = telefone;
		this.contato = contato;
		this.filterRuleJexl = filterRuleJexl;
		this.usuariosNotificados = usuariosNotifcados;
		this.contratos = contratos;
		this.ocorrencias = ocorrencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 500)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "endereco", nullable = false, length = 2000)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "cnpj", nullable = false, length = 14)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "telefone", nullable = false, length = 30)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "contato", nullable = false, length = 2000)
	public String getContato() {
		return this.contato;
	}

	public void setContato(String contato) {
		this.contato = contato;
	}

	@Column(name = "filter_rule_jexl", length = 2000)
	public byte[] getFilterRuleJexl() {
		return this.filterRuleJexl;
	}

	public void setFilterRuleJexl(byte[] filterRuleJexl) {
		this.filterRuleJexl = filterRuleJexl;
	}

	@Column(name = "usuarios_notificados", length = 2000)
	public String getUsuariosNotificados() {
		return this.usuariosNotificados;
	}

	public void setUsuariosNotificados(String usuariosNotificados) {
		this.usuariosNotificados = usuariosNotificados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Contrato> getContratos() {
		return this.contratos;
	}

	public void setContratos(Set<Contrato> contratos) {
		this.contratos = contratos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Ocorrencia> getOcorrencias() {
		return this.ocorrencias;
	}

	public void setOcorrencias(Set<Ocorrencia> ocorrencias) {
		this.ocorrencias = ocorrencias;
	}

}
