package br.com.bluesi.mailmonitor.entities;
// Generated 10/08/2017 21:38:25 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Configuracao generated by hbm2java
 */
@Entity
@Table(name = "configuracao",catalog = "opsblue")
public class Configuracao implements java.io.Serializable {

	private Integer id;
	private String contexto;
	private String valor;
	private String chave;
	private Set<Ocorrencia> ocorrenciasForSituacao = new HashSet<Ocorrencia>(0);
	private Set<Ocorrencia> ocorrenciasForSeveridade = new HashSet<Ocorrencia>(0);

	public Configuracao() {
	}

	public Configuracao(String contexto, String valor, String chave) {
		this.contexto = contexto;
		this.valor = valor;
		this.chave = chave;
	}

	public Configuracao(String contexto, String valor, String chave, Set<Ocorrencia> ocorrenciasForSituacao,
			Set<Ocorrencia> ocorrenciasForSeveridade) {
		this.contexto = contexto;
		this.valor = valor;
		this.chave = chave;
		this.ocorrenciasForSituacao = ocorrenciasForSituacao;
		this.ocorrenciasForSeveridade = ocorrenciasForSeveridade;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "contexto", nullable = false, length = 200)
	public String getContexto() {
		return this.contexto;
	}

	public void setContexto(String contexto) {
		this.contexto = contexto;
	}

	@Column(name = "valor", nullable = false, length = 2000)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "chave", nullable = false, length = 200)
	public String getChave() {
		return this.chave;
	}

	public void setChave(String chave) {
		this.chave = chave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracaoBySituacao")
	public Set<Ocorrencia> getOcorrenciasForSituacao() {
		return this.ocorrenciasForSituacao;
	}

	public void setOcorrenciasForSituacao(Set<Ocorrencia> ocorrenciasForSituacao) {
		this.ocorrenciasForSituacao = ocorrenciasForSituacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracaoBySeveridade")
	public Set<Ocorrencia> getOcorrenciasForSeveridade() {
		return this.ocorrenciasForSeveridade;
	}

	public void setOcorrenciasForSeveridade(Set<Ocorrencia> ocorrenciasForSeveridade) {
		this.ocorrenciasForSeveridade = ocorrenciasForSeveridade;
	}

}
