package br.com.bluesi.mailmonitor.entities;
// Generated 10/08/2017 21:38:25 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name = "contrato",catalog = "opsblue")
public class Contrato implements java.io.Serializable {

	private Integer id;
	private Cliente cliente;
	private String descricaoObj;
	private String link;
	private String gestorContrato;
	private String telefone;
	private String email;
	private String emailService;

	public Contrato() {
	}

	public Contrato(Cliente cliente, String descricaoObj) {
		this.cliente = cliente;
		this.descricaoObj = descricaoObj;
	}

	public Contrato(Cliente cliente, String descricaoObj, String link, String gestorContrato, String telefone,
			String email, String emailService) {
		this.cliente = cliente;
		this.descricaoObj = descricaoObj;
		this.link = link;
		this.gestorContrato = gestorContrato;
		this.telefone = telefone;
		this.email = email;
		this.emailService = emailService;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_id_fk", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "descricao_obj", nullable = false, length = 2000)
	public String getDescricaoObj() {
		return this.descricaoObj;
	}

	public void setDescricaoObj(String descricaoObj) {
		this.descricaoObj = descricaoObj;
	}

	@Column(name = "link", length = 100)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "gestor_contrato", length = 200)
	public String getGestorContrato() {
		return this.gestorContrato;
	}

	public void setGestorContrato(String gestorContrato) {
		this.gestorContrato = gestorContrato;
	}

	@Column(name = "telefone", length = 30)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "email_service", length = 50)
	public String getEmailService() {
		return this.emailService;
	}

	public void setEmailService(String emailService) {
		this.emailService = emailService;
	}

}
