package br.com.bluesi.mailmonitor.entities;
// Generated 10/08/2017 21:38:25 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Interacao generated by hbm2java
 */
@Entity
@Table(name = "interacao",catalog = "opsblue")
public class Interacao implements java.io.Serializable {

	private Integer id;
	private Ocorrencia ocorrencia;
	private Usuario usuario;
	private Date dataHora;
	private String descricao;
	private String anexo;

	public Interacao() {
	}

	public Interacao(Ocorrencia ocorrencia, Usuario usuario, Date dataHora, String descricao) {
		this.ocorrencia = ocorrencia;
		this.usuario = usuario;
		this.dataHora = dataHora;
		this.descricao = descricao;
	}

	public Interacao(Ocorrencia ocorrencia, Usuario usuario, Date dataHora, String descricao, String anexo) {
		this.ocorrencia = ocorrencia;
		this.usuario = usuario;
		this.dataHora = dataHora;
		this.descricao = descricao;
		this.anexo = anexo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ocorrencia_id_fk", nullable = false)
	public Ocorrencia getOcorrencia() {
		return this.ocorrencia;
	}

	public void setOcorrencia(Ocorrencia ocorrencia) {
		this.ocorrencia = ocorrencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id_fk", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora", nullable = false, length = 19)
	public Date getDataHora() {
		return this.dataHora;
	}

	public void setDataHora(Date dataHora) {
		this.dataHora = dataHora;
	}

	@Column(name = "descricao", nullable = false, length = 2000)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "anexo", length = 200)
	public String getAnexo() {
		return this.anexo;
	}

	public void setAnexo(String anexo) {
		this.anexo = anexo;
	}

}
