package br.com.bluesi.mailmonitor.entities;
// Generated 10/08/2017 21:38:25 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogSoBlue generated by hbm2java
 */
@Entity
@Table(name = "log_so_blue",catalog = "opsblue")
public class LogSoBlue implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String entidade;
	private Date dataHora;
	private byte[] txt;

	public LogSoBlue() {
	}

	public LogSoBlue(String nome, String entidade, Date dataHora, byte[] txt) {
		this.nome = nome;
		this.entidade = entidade;
		this.dataHora = dataHora;
		this.txt = txt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 200)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "entidade", nullable = false, length = 200)
	public String getEntidade() {
		return this.entidade;
	}

	public void setEntidade(String entidade) {
		this.entidade = entidade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora", nullable = false, length = 19)
	public Date getDataHora() {
		return this.dataHora;
	}

	public void setDataHora(Date dataHora) {
		this.dataHora = dataHora;
	}

	@Column(name = "txt", nullable = false)
	public byte[] getTxt() {
		return this.txt;
	}

	public void setTxt(byte[] txt) {
		this.txt = txt;
	}

}
