package br.com.bluesi.mailmonitor.entities;
// Generated 10/08/2017 21:38:25 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ocorrencia generated by hbm2java
 */
@Entity
@Table(name = "ocorrencia",catalog = "opsblue")
public class Ocorrencia implements java.io.Serializable {

	private Integer id;
	private AgrupamentoOcorrencia agrupamentoOcorrencia;
	private Cliente cliente;
	private Configuracao configuracaoBySituacao;
	private Configuracao configuracaoBySeveridade;
	private Usuario usuario;
	private String titulo;
	private String descricao;
	private Date dataHora;
	private String attechmentPath;
	private byte[] bodyMsg;
	private String instancia;
	private Set<Interacao> interacaos = new HashSet<Interacao>(0);
	private Set<TagsBlueOcorrencia> tagsBlueOcorrencias = new HashSet<TagsBlueOcorrencia>(0);

	public Ocorrencia() {
	}

	public Ocorrencia(Cliente cliente, String titulo, String descricao, Date dataHora) {
		this.cliente = cliente;
		this.titulo = titulo;
		this.descricao = descricao;
		this.dataHora = dataHora;
	}

	public Ocorrencia(AgrupamentoOcorrencia agrupamentoOcorrencia, Cliente cliente, Configuracao configuracaoBySituacao,
			Configuracao configuracaoBySeveridade, Usuario usuario, String titulo, String descricao, Date dataHora,
			String attechmentPath, byte[] bodyMsg, String instancia, Set<Interacao> interacaos) {
		this.agrupamentoOcorrencia = agrupamentoOcorrencia;
		this.cliente = cliente;
		this.configuracaoBySituacao = configuracaoBySituacao;
		this.configuracaoBySeveridade = configuracaoBySeveridade;
		this.usuario = usuario;
		this.titulo = titulo;
		this.descricao = descricao;
		this.dataHora = dataHora;
		this.attechmentPath = attechmentPath;
		this.bodyMsg = bodyMsg;
		this.instancia = instancia;
		this.interacaos = interacaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agrupamento_id_fk")
	public AgrupamentoOcorrencia getAgrupamentoOcorrencia() {
		return this.agrupamentoOcorrencia;
	}

	public void setAgrupamentoOcorrencia(AgrupamentoOcorrencia agrupamentoOcorrencia) {
		this.agrupamentoOcorrencia = agrupamentoOcorrencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsavel_cliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "situacao")
	public Configuracao getConfiguracaoBySituacao() {
		return this.configuracaoBySituacao;
	}

	public void setConfiguracaoBySituacao(Configuracao configuracaoBySituacao) {
		this.configuracaoBySituacao = configuracaoBySituacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "severidade")
	public Configuracao getConfiguracaoBySeveridade() {
		return this.configuracaoBySeveridade;
	}

	public void setConfiguracaoBySeveridade(Configuracao configuracaoBySeveridade) {
		this.configuracaoBySeveridade = configuracaoBySeveridade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsavel_blue")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "titulo", nullable = false, length = 200)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descricao", nullable = true, length = 2000)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora", nullable = false, length = 19)
	public Date getDataHora() {
		return this.dataHora;
	}

	public void setDataHora(Date dataHora) {
		this.dataHora = dataHora;
	}

	@Column(name = "attechment_path", length = 2000)
	public String getAttechmentPath() {
		return this.attechmentPath;
	}

	public void setAttechmentPath(String attechmentPath) {
		this.attechmentPath = attechmentPath;
	}

	@Column(name = "body_msg")
	public byte[] getBodyMsg() {
		return this.bodyMsg;
	}

	public void setBodyMsg(byte[] bodyMsg) {
		this.bodyMsg = bodyMsg;
	}

	@Column(name = "instancia", length = 200)
	public String getInstancia() {
		return this.instancia;
	}

	public void setInstancia(String instancia) {
		this.instancia = instancia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ocorrencia")
	public Set<Interacao> getInteracaos() {
		return this.interacaos;
	}

	public void setInteracaos(Set<Interacao> interacaos) {
		this.interacaos = interacaos;
	}

}
