package br.com.bluesi.mailmonitor.entities;
// Generated 01/09/2017 00:05:12 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TagBlue generated by hbm2java
 */
@Entity
@Table(name = "tag_blue",catalog = "opsblue", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class TagBlue implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String cor;
	private String sinonimo;
	private Set<TagsBlueOcorrencia> tagsBlueOcorrencias = new HashSet<TagsBlueOcorrencia>(0);

	public TagBlue() {
	}

	public TagBlue(String nome) {
		this.nome = nome;
	}

	public TagBlue(String nome, String cor, String sinonimo, Set<TagsBlueOcorrencia> tagsBlueOcorrencias) {
		this.nome = nome;
		this.cor = cor;
		this.sinonimo = sinonimo;
		this.tagsBlueOcorrencias = tagsBlueOcorrencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", unique = true, nullable = false, length = 20)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cor", length = 20)
	public String getCor() {
		return this.cor;
	}

	public void setCor(String cor) {
		this.cor = cor;
	}

	@Column(name = "sinonimo", length = 20)
	public String getSinonimo() {
		return this.sinonimo;
	}

	public void setSinonimo(String sinonimo) {
		this.sinonimo = sinonimo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tagBlue")
	public Set<TagsBlueOcorrencia> getTagsBlueOcorrencias() {
		return this.tagsBlueOcorrencias;
	}

	public void setTagsBlueOcorrencias(Set<TagsBlueOcorrencia> tagsBlueOcorrencias) {
		this.tagsBlueOcorrencias = tagsBlueOcorrencias;
	}

}
