package br.com.bluesi.mailmonitor.entities;
// Generated 10/08/2017 21:38:25 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario",catalog = "opsblue")
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String email;
	private String telefone;
	private int tipo;
	private int perfil;
	private String nome;
	private String senha;
	private Set<Ocorrencia> ocorrencias = new HashSet<Ocorrencia>(0);
	private Set<Interacao> interacaos = new HashSet<Interacao>(0);

	public Usuario() {
	}

	public Usuario(String email, String telefone, int tipo, int perfil, String nome, String senha) {
		this.email = email;
		this.telefone = telefone;
		this.tipo = tipo;
		this.perfil = perfil;
		this.nome = nome;
		this.senha = senha;
	}

	public Usuario(String email, String telefone, int tipo, int perfil, String nome, String senha,
			Set<Ocorrencia> ocorrencias, Set<Interacao> interacaos) {
		this.email = email;
		this.telefone = telefone;
		this.tipo = tipo;
		this.perfil = perfil;
		this.nome = nome;
		this.senha = senha;
		this.ocorrencias = ocorrencias;
		this.interacaos = interacaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefone", nullable = false, length = 30)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "tipo", nullable = false)
	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	@Column(name = "perfil", nullable = false)
	public int getPerfil() {
		return this.perfil;
	}

	public void setPerfil(int perfil) {
		this.perfil = perfil;
	}

	@Column(name = "nome", nullable = false, length = 200)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "senha", nullable = false, length = 200)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Ocorrencia> getOcorrencias() {
		return this.ocorrencias;
	}

	public void setOcorrencias(Set<Ocorrencia> ocorrencias) {
		this.ocorrencias = ocorrencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Interacao> getInteracaos() {
		return this.interacaos;
	}

	public void setInteracaos(Set<Interacao> interacaos) {
		this.interacaos = interacaos;
	}

}
